-- MySQL Script generated by MySQL Workbench
-- Sun Jun 22 21:31:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cine` DEFAULT CHARACTER SET utf8 ;
USE `cine` ;

-- -----------------------------------------------------
-- Table `cine`.`filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cine`.`filmes` (
  `idfilmes` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL,
  `duracao` TIME NULL,
  `genero` VARCHAR(100) NULL,
  `diretor` VARCHAR(100) NULL,
  PRIMARY KEY (`idfilmes`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
